version: "3.6"
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.3.2
    container_name: filebeat
    restart: always
    user: root
    networks:
      - esnet
    volumes:
      - $PWD/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - $PWD/filebeat-docker/logs:/usr/share/filebeat/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp:ro

networks:
  esnet:
